[project]
name = "laba1-c"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SkankHunt3r42", email = "nikitos77@i.ua" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
laba1-c = "laba1_c:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
